Repository CMPUT301F20T03/OneInfiniteLoop, pull requests merged in 2020-11, with the labels that each got.

#67 Sazimi design
  Booksies/app/src/main/ic_launcher_booksies-playstore.png
  Booksies/app/src/main/res/mipmap-hdpi/ic_launcher_booksies.png
  Booksies/app/src/main/res/mipmap-hdpi/ic_launcher_booksies_foreground.png
  Booksies/app/src/main/res/mipmap-hdpi/ic_launcher_booksies_round.png
  Booksies/app/src/main/res/mipmap-mdpi/ic_launcher_booksies.png
  Booksies/app/src/main/res/mipmap-mdpi/ic_launcher_booksies_foreground.png
  Booksies/app/src/main/res/mipmap-mdpi/ic_launcher_booksies_round.png
  Booksies/app/src/main/res/mipmap-xhdpi/ic_launcher_booksies.png
  Booksies/app/src/main/res/mipmap-xhdpi/ic_launcher_booksies_foreground.png
  Booksies/app/src/main/res/mipmap-xhdpi/ic_launcher_booksies_round.png
  Booksies/app/src/main/res/mipmap-xxhdpi/ic_launcher_booksies.png
  Booksies/app/src/main/res/mipmap-xxhdpi/ic_launcher_booksies_foreground.png
  Booksies/app/src/main/res/mipmap-xxhdpi/ic_launcher_booksies_round.png
  Booksies/app/src/main/res/mipmap-xxxhdpi/ic_launcher_booksies.png
  Booksies/app/src/main/res/mipmap-xxxhdpi/ic_launcher_booksies_foreground.png
  Booksies/app/src/main/res/mipmap-xxxhdpi/ic_launcher_booksies_round.png
Labels: Design

#102 refactor
  Booksies/app/src/main/java/com/example/booksies/controller/EditUserProfileActivity.java
  Booksies/app/src/main/java/com/example/booksies/controller/NavigationActivity.java
  Booksies/app/src/main/java/com/example/booksies/controller/RequestListFragment.java
  Booksies/app/src/main/java/com/example/booksies/model/adapters/BooksListAdapter.java
  Booksies/app/src/main/java/com/example/booksies/model/adapters/BooksListAdapter_Expand.java
  Booksies/app/src/main/java/com/example/booksies/model/adapters/Map_Adapter.java
  Booksies/app/src/main/java/com/example/booksies/model/adapters/RequestListAdapter.java
Labels: refactoring

#105 Sazimi refactoring
  Booksies/app/src/main/java/com/example/booksies/model/adapters/BooksListAdapter.java
  Booksies/app/src/main/java/com/example/booksies/model/adapters/BooksListAdapter_Expand.java
  Booksies/app/src/main/java/com/example/booksies/model/books/Books.java
  Booksies/app/src/main/java/com/example/booksies/model/books/bookIdentifiable.java
  Booksies/app/src/main/java/com/example/booksies/model/books/book_status.java
Labels: documentation

#106 Tony Javadoc
  Booksies/app/src/androidTest/java/com/example/booksies/TransactionTest.java
  Booksies/app/src/androidTest/java/com/example/booksies/UserProfileFragmentTest.java
  Booksies/app/src/main/java/com/example/booksies/controller/EditUserProfileActivity.java
  Booksies/app/src/main/java/com/example/booksies/controller/NavigationActivity.java
  Booksies/app/src/main/java/com/example/booksies/controller/UserProfileFragment.java
  Booksies/app/src/main/java/com/example/booksies/controller/ViewProfileActivity.java
  Booksies/app/src/main/java/com/example/booksies/model/adapters/NotificationAdapter.java
  Booksies/app/src/main/java/com/example/booksies/model/notification/Notification.java
  Booksies/app/src/main/java/com/example/booksies/model/notification/notifiable.java
Labels: documentation

#108 fix back
  Booksies/app/src/main/java/com/example/booksies/controller/HomeFragment.java
  Booksies/app/src/main/java/com/example/booksies/controller/MainActivity.java
  Booksies/app/src/main/java/com/example/booksies/controller/NavigationActivity.java
Labels: Design, bug

#111 do enhancement
  Booksies/app/src/main/java/com/example/booksies/model/database/CRUD.java
  Booksies/app/src/main/java/com/example/booksies/model/database/FirestoreHandler.java
Labels: documentation, enhancement, refactoring
